Repository bitbit-Merry-go-round/Transcendence-FE, pull requests merged in 2024-03, with the labels that each got.

#5 feat(#2): 로그인 화면 구현
  front/srcs/assets/forest.jpeg
  front/srcs/assets/logo.svg
  front/srcs/data/user.js
  front/srcs/index.html
  front/srcs/index.js
  front/srcs/init.js
  front/srcs/lib/binded_view.js
  front/srcs/lib/binding.js
  front/srcs/lib/observable.js
  front/srcs/lib/observable_object.js
  front/srcs/lib/view.js
  front/srcs/router.js
  front/srcs/utils/keypath.js
  front/srcs/views/components/nav_bar.html
  front/srcs/views/components/nav_bar.js
  front/srcs/views/config.js
  front/srcs/views/game/game_view.html
  front/srcs/views/game/game_view.js
  front/srcs/views/home/home_view.html
  front/srcs/views/home/home_view.js
  front/srcs/views/login/login_view.html
  front/srcs/views/login/login_view.js
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#6 feat(#3, #4): nginx 서버 컨테이너 올림
  .env
  Makefile
  compose.yaml
  front/nginx/conf/default.conf
  front/nginx/conf/nginx.conf
  front/nginx/dockerfile
Labels: ✨ Feature

#11 feat: nav-bar #1
  front/srcs/init.js
  front/srcs/views/components/nav_bar.html
  front/srcs/views/components/nav_bar.js
  front/srcs/views/components/profile_card.html
  front/srcs/views/components/profile_card.js
  front/srcs/views/config.js
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#12 feat: home-view
  front/nginx/conf/default.conf
  front/srcs/assets/imac.png
  front/srcs/assets/start.png
  front/srcs/index.html
  front/srcs/styles.css
  front/srcs/views/home/home_view.html
  front/srcs/views/login/login_view.html
Labels: ✨ Feature

#13 feat: #9 프로필 모달
  front/srcs/data/user.js
  front/srcs/views/components/nav_bar.js
  front/srcs/views/components/profile_card.html
  front/srcs/views/components/profile_card.js
Labels: ✨ Feature

#17 feat: #14 친구 목록
  front/nginx/conf/default.conf
  front/srcs/data/user.js
  front/srcs/lib/view.js
  front/srcs/router.js
  front/srcs/styles.css
  front/srcs/views/components/nav_bar.html
  front/srcs/views/components/profile_card.html
  front/srcs/views/config.js
  front/srcs/views/friend/friend_view.html
  front/srcs/views/friend/friend_view.js
  front/srcs/views/home/home_view.html
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#20 feat: #14 친구 목록
  front/srcs/lib/view.js
  front/srcs/router.js
  front/srcs/views/components/nav_bar.js
  front/srcs/views/components/profile_card.html
  front/srcs/views/friend/friend_view.html
  front/srcs/views/friend/friend_view.js
  front/srcs/views/home/home_view.js
Labels: ✨ Feature

#21 feat: #19 전적 조회 페이지
  front/srcs/router.js
  front/srcs/styles.css
  front/srcs/views/components/profile_card.html
  front/srcs/views/config.js
  front/srcs/views/friend/friend_view.html
  front/srcs/views/record/record_view.html
  front/srcs/views/record/record_view.js
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#23 feat: #22
  front/srcs/index.html
  front/srcs/router.js
  front/srcs/styles.css
  front/srcs/views/config.js
  front/srcs/views/home/home_view.html
  front/srcs/views/mode/mode_view.html
  front/srcs/views/mode/mode_view.js
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#25 feat: #24 tournament
  front/srcs/assets/start.png
  front/srcs/router.js
  front/srcs/styles.css
  front/srcs/views/config.js
  front/srcs/views/home/home_view.html
  front/srcs/views/mode/mode_view.html
  front/srcs/views/tournament/tournament_view.html
  front/srcs/views/tournament/tournament_view.js
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#28 Feat/loading
  front/srcs/styles.css
  front/srcs/views/mode/mode_view.html
  front/srcs/views/mode/mode_view.js
Labels: ✨ Feature

#30 feat: #26 매칭 완료 뷰
  front/srcs/router.js
  front/srcs/styles.css
  front/srcs/views/config.js
  front/srcs/views/match/match_view.html
  front/srcs/views/match/match_view.js
  front/srcs/views/mode/mode_view.html
  front/srcs/views/record/record_view.html
  front/srcs/views/viewClasses.js
Labels: ✨ Feature

#36 feat: #35 fetch modules
  front/nginx/conf/default.conf
  front/nginx/conf/nginx.conf
  front/nginx/dockerfile
  front/nginx/tools/run.sh
  front/srcs/package.json
Labels: ✨ Feature

#39 feat: (#18) edit profile
  front/nginx/tools/run.sh
  front/srcs/init.js
  front/srcs/styles.css
  front/srcs/views/components/profile_card.html
  front/srcs/views/config.js
  front/srcs/views/edit/edit_view.html
  front/srcs/views/edit/edit_view.js
  front/srcs/views/friend/friend_view.js
Labels: ✨ Feature

#44 refactor: #41 design-fix
  front/nginx/conf/default.conf
  front/srcs/assets/favicon.ico
  front/srcs/styles.css
  front/srcs/views/components/nav_bar.js
  front/srcs/views/components/profile_card.html
  front/srcs/views/components/profile_card.js
  front/srcs/views/edit/edit_view.js
  front/srcs/views/friend/friend_view.js
  front/srcs/views/home/home_view.js
  front/srcs/views/match/match_view.html
  front/srcs/views/match/match_view.js
  front/srcs/views/mode/mode_view.html
  front/srcs/views/mode/mode_view.js
  front/srcs/views/record/record_view.html
  front/srcs/views/record/record_view.js
Labels: ♻️ Refactor

#45 fix: v0.1.1
  front/nginx/conf/default.conf
  front/srcs/assets/favicon.ico
  front/srcs/data/game_data.js
  front/srcs/data/global.js
  front/srcs/game/game_scene.js
  front/srcs/lib/view.js
  front/srcs/router.js
  front/srcs/styles.css
  front/srcs/utils/image_generator.js
  front/srcs/views/components/nav_bar.js
  front/srcs/views/components/profile_card.html
  front/srcs/views/components/profile_card.js
  front/srcs/views/components/user_label.html
  front/srcs/views/components/user_label.js
  front/srcs/views/config.js
  front/srcs/views/edit/edit_view.js
  front/srcs/views/friend/friend_view.js
  front/srcs/views/game/game_view.js
  front/srcs/views/home/home_view.js
  front/srcs/views/match/match_view.html
  front/srcs/views/match/match_view.js
  front/srcs/views/mode/mode_view.html
  front/srcs/views/mode/mode_view.js
  front/srcs/views/record/record_view.html
  front/srcs/views/record/record_view.js
Labels: 🐛 Bug

#48 feat: fetch data #46
  .gitignore
  front/srcs/styles.css
  front/srcs/views/components/nav_bar.html
  front/srcs/views/components/nav_bar.js
  front/srcs/views/components/profile_card.html
  front/srcs/views/components/profile_card.js
  front/srcs/views/edit/edit_view.html
  front/srcs/views/edit/edit_view.js
  front/srcs/views/friend/friend_view.html
  front/srcs/views/friend/friend_view.js
  front/srcs/views/home/home_view.js
  front/srcs/views/record/record_view.js
Labels: ✨ Feature
